plugins {
    id 'java'
}

group = 'com.arnor4eck'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.github.cdimascio:dotenv-java:3.2.0'
    implementation 'org.postgresql:postgresql:42.7.3'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core:5.23.0'
}

test {
    useJUnitPlatform()
}